CREATE DATABASE MY_SHOP_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE TABLE RAW.CATALOG(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(30),
    CATEGORY VARCHAR(30),
    BASE_PRICE DECIMAL(10,2)
);

CREATE TABLE RAW.USERS(
    USER_ID INT,
    USER_NAME VARCHAR(25),
    CITY VARCHAR(25),
    SIGNUP_DATE TIMESTAMP
);

CREATE TABLE RAW.ORDERS(
    ORDER_ID INT,
    USER_ID INT,
    STATUS_ID INT,
    ORDER_TIMESTAMP TIMESTAMP
);

CREATE TABLE RAW.ORDER_STATUS(
    STATUS_ID INT,
    STATUS_NAME VARCHAR(30)
);

CREATE TABLE RAW.ORDER_ITEMS(
    ITEM_ID INT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    PRICE_AT_MOMENT DECIMAL(10,2)
);